apiVersion: apps/v1
kind: Deployment

metadata:
  name: login-service

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: login-service

  template:
    metadata:
      labels:
        app: login-service

    spec:
      containers:
        - name: login-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: {{ .Values.containerPort }}
