name: Login Service CI

on:
  pull_request:
    branches:
      - main

jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Execute Permission
        run: chmod +x mvnw

      - name: Build Application
        run: ./mvnw clean compile

      - name: Run Unit Tests
        run: ./mvnw test

      - name: Package JAR
        run: ./mvnw clean package
